### PR TITLE
Hdl atmegaxx0_1 (Interruptions)

### PR DESCRIPTION
**Pull request by astralien3000**
Here it is !
The interruptions are now managed by HDL (and not by the avr-libc anymore).
Moreover, the interruptions are now templatized !

But there is a little drawback to the system... Indeed, GCC check if a "signal" function (aka an interruption) has it's name begining with "_vector", which is not the case of the mangled names of the new interruptions.
So, the compiler will show this warning if you use the new interuption system : 
```
warning: '...' appears to be a misspelled signal handler
```

But this is a verification the compiler should not do ? Well, he actually should in most of the cases, but not this one. And there is no option to disable this warning.

### CODE REVIEW

**Comment by astralien3000** [comment]
The "bug" of avr-gcc [has been posted](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68199), let's see what happens !

**Comment by Elioty** [comment]
No `-Wno-something`option in avr-gcc to turn off that warning?! It's a shame...

Anyway, great job on making it to the GCC bug tracker. You made sure there wasn't any issue about that already, right? :yum: However, if they remove that warning or make an option to mute it, the change will certainly not be back-ported to GCC 4.8 branch so we will have that warning for a (very) long time before we find it appropriate to jump to a newer GCC version, once that new GCC version is widely spread across many Linux distributions (and both for x86, ARM and AVR).

And as we discussed, you only handle UART interrupts for now. You forgot about the timer and the GPIO modules.

**Comment by astralien3000** [comment]
Actually, there is an other bug mentioning it, I first thought the issue was about adding an option to transform the warning into an error, but it also deals with an option to remove this warning.
But my issue is more complete !
I know where the verification is done in avr-gcc, but I have no idea on how to add an option... So that it would be hard for me to propose a patch to gcc currently.

**Comment by astralien3000** [comment]
Done ! I had to add a new module to configure "GPIO" interruptions.
I also added some examples/tests for each type of interruption.

**Pull request merged**
